version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: node:latest
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package-lock.json" }}
      - run:
          name: Get token
          command: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ${HOME}/.npmrc
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/
      - run:
          name: ESLint
          command: npm run lint
      - run:
          name: Build
          command: npm run build
      - run:
          name: Minify
          command: npm run minify
      - store_artifacts:
          path: dist/
      - deploy:
          name: Release
          command: |
            if [[ $CIRCLE_TAG =~ v.* && $CIRCLE_PROJECT_USERNAME == "ft-interactive" ]]; then
              npm-prepublish --verbose
              npm publish --access public
            fi
